# Generated by Django 4.2.6 on 2023-11-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_account_number_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='debit_card_limit',
            new_name='account_debit_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='overdraft_limit',
        ),
    ]
