# Generated by Django 4.2.6 on 2023-11-01 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_by', to=settings.AUTH_USER_MODEL)),
                ('payed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
